# Site settings
title: F&P UTM Builder
description: Marketing UTM Parameter Builder and Manager
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Custom variables
company_name: Fisher & Paykel
version: 1.0.0

# Layout settings
show_downloads: false
google_analytics: # Add your GA tag if needed
